#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
echo "This is the setup script"

echo "####################################################"
echo "# Verifying Porosimo Edge's are deployed and ready #"
echo "####################################################"

ALL_EDGE_READY=false
EDGE_DEPLOY_STATUS_ARR=""
while [ "$ALL_EDGE_READY" = false ]
do
  EDGE_DEPLOY_STATUS_ARR=($(curl -s https://${INSTRUQT_PARTICIPANT_ID}.admin.prosimo.io/api/prosimo/app \
 -H "Content-Type: application/json" \
 -H "Prosimo-ApiToken: ${TF_VAR_prosimo_token}" | jq -r '.data[] | .status'))

  EDGE_READY_COUNT=0

  for i in ${EDGE_DEPLOY_STATUS_ARR[@]}
  do
    if [ "$i" = "DEPLOYED" ]
    then
      EDGE_READY_COUNT=$((EDGE_READY_COUNT + 1))
    fi
  done

  ARR_LEN=${#EDGE_DEPLOY_STATUS_ARR[@]}

  if [ "$EDGE_READY_COUNT" -eq "$ARR_LEN" ]
  then
    echo "#############################################"
    echo "# All Edges are Deployed and READY!!! Yay!! #"
    echo "#############################################"
    ALL_EDGE_READY=true
  else
    echo "All Edges are NOT READY yet."
    echo "Retrying API for Edge Status in 60 seconds"
    sleep 60
  fi
done 


echo "#####################################################"
echo "# START - Prosimo: Namespace creation and exporting #"
echo "#####################################################"

cd /root/prosimo-lab/assets/terraform/prosimo_infra/namespaces
terraform init
sleep 5

terraform apply -auto-approve \
 -var prosimo_token=${TF_VAR_prosimo_token} \
 -var prosimo_team_name=${INSTRUQT_PARTICIPANT_ID}

echo "Sleeping 1 mins before commencing Prosimo Network Onboarding..."
sleep 60
echo "Awake!!"

echo "######################################################"
echo "# END - Prosimo: Namespace creation and exporting #"
echo "######################################################"



echo "########################################################"
echo "# START - Prosimo: Onboarding Networks - AWS eu-west-1 #"
echo "########################################################"

cd /root/prosimo-lab/assets/terraform/prosimo_infra/onboard_network_aws_eu_west_1
terraform init
sleep 5

terraform apply -auto-approve \
 -var prosimo_token=${TF_VAR_prosimo_token} \
 -var prosimo_team_name=${INSTRUQT_PARTICIPANT_ID} \
 -var aws_access_key_id=${INSTRUQT_AWS_ACCOUNT_PROSIMO_DEMO_AWS_ACCESS_KEY_ID} \
 -var aws_secret_key_id=${INSTRUQT_AWS_ACCOUNT_PROSIMO_DEMO_AWS_SECRET_ACCESS_KEY}

echo "Sleeping 1 mins before next Prosimo Network Onboarding..."
sleep 60
echo "Awake!!"

echo "######################################################"
echo "# END - Prosimo: Onboarding Networks - AWS eu-west-1 #"
echo "######################################################"


echo "########################################################"
echo "# START - Prosimo: Onboarding Networks - AWS us-east-1 #"
echo "########################################################"

cd /root/prosimo-lab/assets/terraform/prosimo_infra/onboard_network_aws_us_east_1

terraform init
sleep 5

terraform apply -auto-approve \
 -var prosimo_token=${TF_VAR_prosimo_token} \
 -var prosimo_team_name=${INSTRUQT_PARTICIPANT_ID} \
 -var aws_access_key_id=${INSTRUQT_AWS_ACCOUNT_PROSIMO_DEMO_AWS_ACCESS_KEY_ID} \
 -var aws_secret_key_id=${INSTRUQT_AWS_ACCOUNT_PROSIMO_DEMO_AWS_SECRET_ACCESS_KEY}

# echo "Sleeping 1 mins before next Prosimo Network Onboarding..."
# sleep 60
# echo "Awake!!"

echo "######################################################"
echo "# END - Prosimo: Onboarding Networks - AWS us-east-1 #"
echo "######################################################"


# echo "############################################################"
# echo "# START - Prosimo: Onboarding Networks - Azure northeurope #"
# echo "############################################################"
# 
# cd /root/prosimo-lab/assets/terraform/prosimo_infra/onboard_network_azure_northeurope
# terraform init
# sleep 5
# 
# terraform apply -auto-approve \
#  -var prosimo_token=${TF_VAR_prosimo_token} \
#  -var prosimo_team_name=${INSTRUQT_PARTICIPANT_ID} \
#  -var azure_subscription_id=${INSTRUQT_AZURE_SUBSCRIPTION_PROSIMO_TENANT_SUBSCRIPTION_ID} \
#  -var azure_tenant_id=${INSTRUQT_AZURE_SUBSCRIPTION_PROSIMO_TENANT_TENANT_ID} \
#  -var azure_client_id=${INSTRUQT_AZURE_SUBSCRIPTION_PROSIMO_TENANT_SPN_ID} \
#  -var azure_client_secret=${INSTRUQT_AZURE_SUBSCRIPTION_PROSIMO_TENANT_SPN_PASSWORD}
# 
# echo "##########################################################"
# echo "# END - Prosimo: Onboarding Networks - Azure northeurope #"
# echo "##########################################################"


set-workdir /root/prosimo-lab

exit 0
